// Comprehensive catalog mapping for Solutions & Digital subpages
// Each subcategory contains 45-50 specialized A-Z services

export interface ServiceDetail {
  id: string;
  name: string;
  desc: string;
}

export interface SubcategoryData {
  title: string;
  parent: "solutions" | "digital";
  tagline: string;
  description: string;
  services: ServiceDetail[];
}

export const servicesData: Record<string, SubcategoryData> = {
  "web-development": {
    title: "Website & E-Commerce Development",
    parent: "solutions",
    tagline: "High-performance websites and digital stores built for growth.",
    description: "Bespoke full-stack development using state-of-the-art frameworks. Clean code, local integrations, database engineering, and bulletproof security layers.",
    services: [
      { id: "W1", name: "Custom Next.js Frontend Development", desc: "Interactive user interfaces built with React and Next.js server components for optimal speeds." },
      { id: "W2", name: "Tailwind CSS Layout & UI Styling", desc: "Premium mobile-responsive custom styling with zero bloated scripts." },
      { id: "W3", name: "Shopify E-Commerce Store Design", desc: "Setting up shop templates, customized cart structures, and sales triggers." },
      { id: "W4", name: "WooCommerce Solutions", desc: "WordPress shopping carts built on optimized hosting configurations." },
      { id: "W5", name: "GCC Payment Gateway Integrations", desc: "Seamless configuration of Tabby, Tamara, PayTabs, MyFatoorah, and Tap Payments." },
      { id: "W6", name: "Razorpay & UPI Indian Gateway Support", desc: "Instant mobile scans and netbanking checkouts configured for Indian customers." },
      { id: "W7", name: "Headless Commerce Implementations", desc: "Decoupled commerce backends connected to React frontends for extreme speed." },
      { id: "W8", name: "RESTful API Development & Configs", desc: "Secure node backends exposing standard JSON APIs for internal apps." },
      { id: "W9", name: "GraphQL Schema Design & Optimization", desc: "Fast data queries using unified endpoints to avoid roundtrip database lags." },
      { id: "W10", name: "PostgreSQL Database Architecture", desc: "Relational database schema modeling, connection pools, and high-load indexing." },
      { id: "W11", name: "MongoDB NoSQL Integrations", desc: "Flexible document stores optimized for user logs, catalog specs, and notifications." },
      { id: "W12", name: "Redis In-Memory Database Configurations", desc: "Setup caching layers to speed up page loads and user session data." },
      { id: "W13", name: "WordPress Headless Configurations", desc: "Utilize WordPress as a CMS back-office while rendering on high-speed Next.js." },
      { id: "W14", name: "Custom CRM & ERP Integrations", desc: "Connect your front-facing websites to SAP, Zoho CRM, Salesforce, or Odoo ERP." },
      { id: "W15", name: "Real-Time Chat WebSockets Integration", desc: "Interactive customer portals featuring socket-based chat windows." },
      { id: "W16", name: "Stripe & PayPal Global Gateways", desc: "Configure multi-currency international checkouts with automated VAT handling." },
      { id: "W17", name: "Progressive Web App (PWA) Development", desc: "Offline storage support, service workers, and installable icons for Android and iOS." },
      { id: "W18", name: "Custom Admin Dashboards & Panels", desc: "Bespoke control panels for staff edits, inventory updates, and order statistics." },
      { id: "W19", name: "Sanity.io & Contentful CMS Setup", desc: "Tailored headless CMS workspaces allowing content writers to make edits safely." },
      { id: "W20", name: "Single-Page Application (SPA) Routing", desc: "Fluid transitions between page screens without full browser reloads." },
      { id: "W21", name: "Static Site Generation (SSG) Compiles", desc: "Pre-compile website screens into flat HTML/CSS assets for near-instant rendering." },
      { id: "W22", name: "Server-Side Rendering (SSR) Setups", desc: "Compile page content dynamically on the server for real-time data accuracy." },
      { id: "W23", name: "Web Security Audits & SSL Setups", desc: "Inject secure HTTPS locks, patch XSS scripts, and implement CORS rules." },
      { id: "W24", name: "Dynamic Forms & File Upload Handlers", desc: "Secure input fields with validation and automatic AWS S3 file hosting." },
      { id: "W25", name: "Cross-Browser Compatibility Fixes", desc: "Guarantee CSS compatibility across Chrome, Safari, Firefox, and legacy screens." },
      { id: "W26", name: "Core Web Vitals Speed Auditing", desc: "Optimize image formats, minimize script payloads, and maximize Lighthouse scores." },
      { id: "W27", name: "CSS Grid & Flexbox Modernizations", desc: "Convert outdated table/float frameworks into modern clean visual alignments." },
      { id: "W28", name: "Localization & Multi-Language Setups", desc: "Setup RTL (Arabic) alignments and translation files for GCC businesses." },
      { id: "W29", name: "Algolia & ElasticSearch Integrations", desc: "Deploy AI-driven instant product search fields in catalog shopping apps." },
      { id: "W30", name: "Automated Testing & Jest Assertions", desc: "Deploy unit testing files to catch syntax bugs before live pushes." },
      { id: "W31", name: "User Auth via NextAuth / Auth0", desc: "Multi-factor authentication, Google logins, and secure JSON Web Tokens." },
      { id: "W32", name: "SaaS Multi-Tenant Database Isolation", desc: "Bespoke database route parameters for subscription SaaS applications." },
      { id: "W33", name: "Serverless Function Deployments", desc: "Setup microservice endpoint scripts on AWS Lambda or Vercel Edge." },
      { id: "W34", name: "Dynamic Invoice & PDF Generation", desc: "Auto-create purchase invoices and digital tickets right in user accounts." },
      { id: "W35", name: "Web App Notification Systems", desc: "Configure browser push messages and automated customer email alerts." },
      { id: "W36", name: "Digital Asset Download Portals", desc: "Secure links with expiry timers to distribute premium files and PDFs." },
      { id: "W37", name: "Performance Profiling & Bundle Sweeps", desc: "Clean up heavy npm dependencies and bundle files to compress page weight." },
      { id: "W38", name: "Interactive Charts via Recharts/D3", desc: "Visualize business trends and data matrices directly on user portals." },
      { id: "W39", name: "Custom Video Player Integrations", desc: "Deploy video sliders with auto-buffering, speed logs, and analytics tracking." },
      { id: "W40", name: "Broken Link Sweeps & Redirect Setup", desc: "Map legacy page paths using 301 redirects to maintain search index scores." },
      { id: "W41", name: "Web Crawler Optimizations (Robots.txt)", desc: "Configure bot traversal permissions to keep private admin screens secure." },
      { id: "W42", name: "Google Tag Manager Implementations", desc: "Unified analytics tag routing without slowing down core web render scripts." },
      { id: "W43", name: "Micro-Frontend Implementations", desc: "Decouple massive dashboard modules allowing teams to edit segments independently." },
      { id: "W44", name: "Web Audio & Custom Sound Effects", desc: "Inject ambient sounds, button tones, and custom sound design systems." },
      { id: "W45", name: "Lottie Vector Animations Setup", desc: "Embed ultra-light vector illustrations that animate dynamically on scroll." },
      { id: "W46", name: "W3C Validation & Coding Standards", desc: "Clean up syntax warnings to verify cross-platform accessibility protocols." }
    ]
  },
  "ai-automation": {
    title: "AI Automation & Smart Chatbots",
    parent: "solutions",
    tagline: "Harness artificial intelligence to automate your business workflows.",
    description: "Integration of custom LLM conversational systems, autonomous document extraction, automated lead scoring, and automated backend scripts.",
    services: [
      { id: "A1", name: "Custom LLM Integrations (OpenAI / LLaMA)", desc: "Connect models to your private corporate database files safely." },
      { id: "A2", name: "RAG (Retrieval-Augmented Generation)", desc: "Build systems that answer queries by searching corporate PDFs and guides." },
      { id: "A3", name: "Custom Lead Generation Chatbots", desc: "Conversational agents that pre-qualify customers and log contacts to CRM." },
      { id: "A4", name: "Customer Support Automation Bots", desc: "Automate responses to frequently asked tickets using tailored agent scripts." },
      { id: "A5", name: "Vector Database Setup (Pinecone/Chroma)", desc: "Establish search indices to feed context to conversational AI models." },
      { id: "A6", name: "Automated Document Parsers", desc: "AI scanners that extract transaction values, dates, and names from invoices." },
      { id: "A7", name: "LangChain & LlamaIndex Workflows", desc: "Chain multiple AI models together to complete multi-step tasks." },
      { id: "A8", name: "N8N & Make.com Automation Setup", desc: "Visually map and automate data transfers across 500+ SaaS apps." },
      { id: "A9", name: "Sentiment Analysis Pipelines", desc: "Scan support feedback to isolate angry clients and alert managers." },
      { id: "A10", name: "Automated Email Draft Generators", desc: "Generate customer replies using context extracted from incoming messages." },
      { id: "A11", name: "AI Invoice Reconciliations", desc: "Compare billing sheets against banking histories to catch mismatch issues." },
      { id: "A12", name: "Optical Character Recognition (OCR)", desc: "Transform handwritten forms and receipts into editable data tables." },
      { id: "A13", name: "Dynamic Price Optimization Scripts", desc: "Monitor competitors and automatically shift pricing using target buffers." },
      { id: "A14", name: "AI Speech-to-Text Transcription", desc: "Transcribe meetings, log action items, and upload reports to databases." },
      { id: "A15", name: "Predictive Analytics Forecast Models", desc: "Estimate demand curves and inventory orders using historic logs." },
      { id: "A16", name: "Automated Lead Scoring Setups", desc: "Score leads using activity metrics and prioritize them for sales agents." },
      { id: "A17", name: "Product Recommendation Engines", desc: "Upsell related catalog items based on historical shopping profiles." },
      { id: "A18", name: "AI-Powered SEO Article Outlines", desc: "Automate blog structures using target search index densities." },
      { id: "A19", name: "Autonomous Social Media Poster", desc: "Draft and queue social media text posts using keyword triggers." },
      { id: "A20", name: "Language Translation Microservices", desc: "Translate incoming customer queries to support local operations." },
      { id: "A21", name: "Automated QA Code Checking", desc: "Run AI code audits to patch bugs before deploying applications." },
      { id: "A22", name: "Data Anonymization Sweeps", desc: "Strip private customer info (PII) before sending files to AI APIs." },
      { id: "A23", name: "Custom Voice Assistant Deployments", desc: "Deploy voice agents that handle initial phone call screenings." },
      { id: "A24", name: "Anomaly Detection Pipelines", desc: "Isolate abnormal billing events and system intrusions in real time." },
      { id: "A25", name: "Automatic Meeting Summarizers", desc: "Summarize transcript files into key bullets, tasks, and deadlines." },
      { id: "A26", name: "AI Resume & Application Screeners", desc: "Identify top candidate profiles using custom qualification filters." },
      { id: "A27", name: "Competitor Web Scraping Pipelines", desc: "Monitor competitor updates, feature shifts, and price listings." },
      { id: "A28", name: "Automatic Contract Review Audits", desc: "Scan agreements to flag risky indemnity terms and exit windows." },
      { id: "A29", name: "AI Image Tagging & Moderation", desc: "Categorize user-uploaded images and block unsafe material automatically." },
      { id: "A30", name: "Predictive Maintenance Algorithms", desc: "Identify equipment wear-and-tear thresholds using hardware logs." },
      { id: "A31", name: "Automated FAQ Page Generators", desc: "Create help pages dynamically by indexing historical chat tickets." },
      { id: "A32", name: "Custom Chatbot Widget Embeds", desc: "Deploy lightweight, brand-aligned floating chat boxes onto sites." },
      { id: "A33", name: "Prompt Injection Security Patches", desc: "Audit chatbot filters to prevent users from bypassing base logic." },
      { id: "A34", name: "Hugging Face Model Fine-Tuning", desc: "Train lightweight open-source models for highly specific tasks." },
      { id: "A35", name: "AI-Driven Feedback Loop Models", desc: "Continually feed corrected chatbot answers back into vector indices." },
      { id: "A36", name: "Workflow Execution Alert Hooks", desc: "Trigger SMS/Slack alerts whenever automated backend pipelines stall." },
      { id: "A37", name: "Automated E-Commerce Order Fulfillers", desc: "Match cart purchases to dropship interfaces without manual entry." },
      { id: "A38", name: "Dynamic Chat Routing Protocols", desc: "Pass complex chatbot conversations to live humans when needed." },
      { id: "A39", name: "Automatic Metadata Generators", desc: "Index large image catalogs by adding descriptions and search tags." },
      { id: "A40", name: "Automated Slack & Discord Assistants", desc: "Manage internal groups, assign roles, and answer staff questions." },
      { id: "A41", name: "Custom OpenAI GPT Store Setup", desc: "Publish tailored GPT tools for internal corporate use cases." },
      { id: "A42", name: "Text Summarizer Widget Configs", desc: "Shorten long corporate reports and contracts into brief paragraphs." },
      { id: "A43", name: "LLM Output Token Optimizations", desc: "Write strict prompts to reduce token usage and API bills." },
      { id: "A44", name: "AI Marketing Campaign Drafts", desc: "Generate custom campaign copy based on target audience profiles." },
      { id: "A45", name: "Custom Agent Tool Implementations", desc: "Equip bots with custom tools to run database searches and calculations." }
    ]
  },
  "cloud-services": {
    title: "Cloud Infrastructure & Microsoft 365",
    parent: "solutions",
    tagline: "Scalable, secure, and reliable cloud structures for modern teams.",
    description: "Enterprise Microsoft 365 licensing, AWS migration blueprints, hourly automated backups, secure spam filters, and database buffer optimizations.",
    services: [
      { id: "C1", name: "Microsoft 365 Tenant Initial Setup", desc: "Establish business domains, configure admin consoles, and assign licenses." },
      { id: "C2", name: "Corporate Microsoft Teams Deployments", desc: "Setup shared team channels, storage folders, and calendar syncs." },
      { id: "C3", name: "Microsoft Outlook MX & DNS Routing", desc: "Configure MX, SPF, DKIM, and DMARC parameters to stop email spoofing." },
      { id: "C4", name: "AWS Instance Configuration (EC2)", desc: "Deploy scalable virtual servers with optimized CPU and storage buffers." },
      { id: "C5", name: "Google Cloud Platform (GCP) Migrations", desc: "Transfer local server applications to GCP with zero business downtime." },
      { id: "C6", name: "Automated Hourly Backup Vaults", desc: "Implement redundant backups to secure files against ransomware." },
      { id: "C7", name: "Cloud Security Audits & Sweeps", desc: "Lock unused network ports, restrict root access, and check security rules." },
      { id: "C8", name: "Microsoft OneDrive Corporate Audits", desc: "Configure access rules to prevent internal file leaks." },
      { id: "C9", name: "Nginx Server Tuning & Optimization", desc: "Configure caching, compression, and request limits for high speeds." },
      { id: "C10", name: "Docker Container Deployments", desc: "Package code into lightweight containers for consistent running." },
      { id: "C11", name: "Kubernetes Orchestration Setups", desc: "Manage multi-container clusters, enabling automatic application scaling." },
      { id: "C12", name: "SPF & DKIM Email Validation", desc: "Fix DNS records to ensure corporate emails arrive in client inboxes." },
      { id: "C13", name: "Anti-Spam Filter Configuration", desc: "Deploy filters to block phishing attempts, viruses, and malware." },
      { id: "C14", name: "Cloudflare CDN & DDoS Protection", desc: "Shield websites from bots and distribute content globally for fast loads." },
      { id: "C15", name: "SSL/TLS Certificate Configurations", desc: "Install and automate SSL updates across all domains and APIs." },
      { id: "C16", name: "AWS S3 File Storage Architecture", desc: "Setup secure buckets for corporate images, files, and database backups." },
      { id: "C17", name: "Database Buffer Optimization", desc: "Fine-tune configuration files to maximize search speeds." },
      { id: "C18", name: "VPN & Secure Remote Access", desc: "Setup secure networks allowing remote teams to access data safely." },
      { id: "C19", name: "Active Directory (AD) Configuration", desc: "Unified password controls and domain access rules for staff." },
      { id: "C20", name: "Microsoft SharePoint Site Design", desc: "Establish intranets for team wikis, templates, and handbooks." },
      { id: "C21", name: "AWS CloudFront Distribution Setups", desc: "Deploy global edge locations to serve asset files instantly." },
      { id: "C22", name: "Disaster Recovery Testing & Manuals", desc: "Document emergency plans and run restore tests to verify backups." },
      { id: "C23", name: "Cloud Cost Optimization Sweeps", desc: "Identify unused instances to cut bloated cloud billing files." },
      { id: "C24", name: "Microsoft Exchange Email Migration", desc: "Transfer active mail histories from local servers to Microsoft 365." },
      { id: "C25", name: "IAM Security Access Control", desc: "Establish strict access rules to enforce least-privilege protocols." },
      { id: "C26", name: "Linux Server Patching & Hardening", desc: "Update kernel scripts, block root SSH logins, and install firewalls." },
      { id: "C27", name: "Redis Cache Clusters Setup", desc: "Deploy database caching to support high concurrent user loads." },
      { id: "C28", name: "Microsoft Intune Device Management", desc: "Secure company laptops, manage updates, and wipe lost devices remotely." },
      { id: "C29", name: "Azure Active Directory Integrations", desc: "Setup Single Sign-On (SSO) to log into SaaS tools with corporate emails." },
      { id: "C30", name: "AWS RDS Automated Clustering", desc: "Setup database servers with automatic failovers to prevent downtime." },
      { id: "C31", name: "SSH Key Authentication Frameworks", desc: "Enforce SSH key-based logins and disable password logins." },
      { id: "C32", name: "Server Resource Monitoring (Grafana)", desc: "Build visual dashboards tracking memory, storage, and network loads." },
      { id: "C33", name: "Email List Quarantine Cleanses", desc: "Clear domain IPs from email spam lists and rebuild sender reputation." },
      { id: "C34", name: "Infrastructure as Code (Terraform)", desc: "Write scripts to deploy and manage server setups automatically." },
      { id: "C35", name: "Load Balancer Configurations", desc: "Distribute incoming web traffic across multiple servers." },
      { id: "C36", name: "GCP BigQuery Data Warehousing", desc: "Setup analytics platforms to process large volumes of user logs." },
      { id: "C37", name: "Microsoft 365 Security Checkups", desc: "Audit user access logs and check spam routing reports." },
      { id: "C38", name: "GitLab & GitHub CI/CD Pipelines", desc: "Automate code compilation and deployment to cloud servers." },
      { id: "C39", name: "Virtual Private Cloud (VPC) Peering", desc: "Connect private database servers to public web instances securely." },
      { id: "C40", name: "SaaS Application Security Audits", desc: "Check API keys and configure webhooks to secure custom platforms." },
      { id: "C41", name: "Cloud Migration Strategy Consulting", desc: "Map infrastructure dependencies and draft step-by-step migration plans." },
      { id: "C42", name: "Microsoft Exchange Online Archiving", desc: "Configure retention rules and secure storage for legacy emails." },
      { id: "C43", name: "AWS Lambda Event-Driven Triggers", desc: "Run code scripts in response to database changes or file uploads." },
      { id: "C44", name: "Database Replication Architectures", desc: "Deploy read-only replica databases to speed up reporting and queries." },
      { id: "C45", name: "Multi-Cloud Redundancy Setup", desc: "Establish backup servers on GCP to run if AWS goes offline." }
    ]
  },
  "video-generation": {
    title: "AI Video Generation & Production",
    parent: "solutions",
    tagline: "Stunning cinematic output and automated video generation engines.",
    description: "AI-driven promo videos, commercial post-production, 3D typography, logo animations, and short-form reels for social channels.",
    services: [
      { id: "V1", name: "AI Video Generation Pipelines", desc: "Use text-to-video tools to draft marketing assets at scale." },
      { id: "V2", name: "Cinematic Corporate Brand Films", desc: "Create high-end video presentations highlighting corporate milestones." },
      { id: "V3", name: "3D Kinetic Typography Animations", desc: "Design eye-catching text animations to boost message impact." },
      { id: "V4", name: "Short-Form Social Media Reels", desc: "Format video clips for optimal engagement on TikTok and Instagram." },
      { id: "V5", name: "AI Avatar Tutorial Videos", desc: "Deploy digital presenters to narrate customer guides and updates." },
      { id: "V6", name: "High-End Color Grading (Log/RAW)", desc: "Apply professional color adjustments to match your brand style." },
      { id: "V7", name: "Professional Video Post-Production", desc: "Review footage, select take sequences, and edit clips into a cohesive story." },
      { id: "V8", name: "Advanced Audio Mix & Sound Design", desc: "Add voiceovers, background music tracks, and custom sound effects." },
      { id: "V9", name: "3D Logo Animations", desc: "Animate corporate logos for use as intro and outro clips." },
      { id: "V10", name: "Commercial Concept Development", desc: "Draft visual treatments, write scripts, and outline storyboard guides." },
      { id: "V11", name: "Commercial Product Video Ads", desc: "Highlight product features using close-up shots and animated text overlays." },
      { id: "V12", name: "Explainer Motion Graphics Projects", desc: "Animate vector illustrations to explain complex software features." },
      { id: "V13", name: "AI Voiceover Cloning & Dubbing", desc: "Translate videos into multiple languages using voice cloning." },
      { id: "V14", name: "Cinematic Transition Effects", desc: "Create smooth visual transitions between video scenes." },
      { id: "V15", name: "Real Estate Promotional Videos", desc: "Create high-impact virtual walkthroughs highlighting property features." },
      { id: "V16", name: "Event Highlight Reel Production", desc: "Edit event recordings into energetic summary clips for social sharing." },
      { id: "V17", name: "Green Screen Keying & Compositing", desc: "Isolate subjects from color backdrops and integrate new background assets." },
      { id: "V18", name: "Video Compression & Format Export", desc: "Optimize export settings to compress video files without losing visual clarity." },
      { id: "V19", name: "Subtitles & Automated Captions", desc: "Generate text overlays to make videos accessible on silent feeds." },
      { id: "V20", name: "Commercial Video Ad Split-Testing", desc: "Edit different versions of ads to test visual variations on social feeds." },
      { id: "V21", name: "Visual Effects (VFX) Tracking", desc: "Integrate text layers and animated elements into moving footage." },
      { id: "V22", name: "Cinematic Drone Footage Edits", desc: "Incorporate aerial footage into brand presentations." },
      { id: "V23", name: "Testimonial Interview Videography", desc: "Record customer reviews and edit them into trust-building assets." },
      { id: "V24", name: "Video Speed Ramping & Retiming", desc: "Adjust playback speeds to match music tracks and highlight key actions." },
      { id: "V25", name: "Social Media Video Banner Design", desc: "Create animated header loops for LinkedIn, YouTube, and website landing pages." },
      { id: "V26", name: "AI Scriptwriting & Copywriting", desc: "Generate script concepts and taglines tailored for specific audiences." },
      { id: "V27", name: "Visual Treatment Pre-Production", desc: "Develop mood boards outlining color directions and visual reference files." },
      { id: "V28", name: "Camera Gear Setup Configurations", desc: "Select cameras, lenses, and lighting equipment to meet project budgets." },
      { id: "V29", name: "Behind-The-Scenes Video Capturing", desc: "Record BTS footage to showcase corporate culture and design processes." },
      { id: "V30", name: "Commercial Sound FX Catalog Routing", desc: "License high-quality sound effects to elevate overall video projects." },
      { id: "V31", name: "TikTok Creative Center Trend Analysis", desc: "Audit visual trends to align video concepts with social algorithms." },
      { id: "V32", name: "Digital Noise Reduction (DNR) Sweeps", desc: "Clean up low-light noise to make footage look clean." },
      { id: "V33", name: "Multi-Camera Video Synchronization", desc: "Align audio waveforms across multiple cameras to simplify edits." },
      { id: "V34", name: "Commercial Aspect Ratio Adapting", desc: "Format master clips into square, vertical, and horizontal versions." },
      { id: "V35", name: "Cinematic End Card Design", desc: "Design animated endings prompting viewers to click websites or call." },
      { id: "V36", name: "Virtual Studio Background Setups", desc: "Create virtual sets to display behind presenters in interviews." },
      { id: "V37", name: "Social Ad Hook Variations Rendering", desc: "Render multiple opening sequences to test which hook holds viewer attention." },
      { id: "V38", name: "Product Spotlight Light Control", desc: "Highlight product features using close-up shots and animated text overlays." },
      { id: "V39", name: "VFX Masking & Object Removal", desc: "Remove unwanted elements from background shots." },
      { id: "V40", name: "Audio Equalization & Vocal Cleanups", desc: "Clear background hums and room echo to make voice tracks sound clear." },
      { id: "V41", name: "Social Story Format Optimizations", desc: "Edit vertical clips optimized for quick views on Instagram and WhatsApp." },
      { id: "V42", name: "AI Video Upscaling (1080p to 4K)", desc: "Improve legacy video files using advanced upscaling tools." },
      { id: "V43", name: "Video Metadata Tagging (YouTube/Vimeo)", desc: "Add video tags and titles to maximize online discoverability." },
      { id: "V44", name: "Licensing Stock Music Routing", desc: "Select and license background music tracks to enhance video stories." },
      { id: "V45", name: "Interactive Video Hotspot Interfaces", desc: "Build web player interfaces with clickable links embedded in videos." }
    ]
  },
  "growth-marketing": {
    title: "A-Z Growth Marketing",
    parent: "digital",
    tagline: "High-yield marketing campaigns and structured growth funnels.",
    description: "End-to-end user acquisition, target audience segment modeling, landing page designs, and technical search tracking structures.",
    services: [
      { id: "M1", name: "Full-Funnel Acquisition Strategy", desc: "Design marketing funnels to capture leads, convert sales, and build loyalty." },
      { id: "M2", name: "Google Search Ads Management (SEM)", desc: "Setup target keywords, write ad copy, and optimize conversion bids." },
      { id: "M3", name: "Facebook & Instagram Paid Campaigns", desc: "Run ads targeting specific demographics to scale product sales." },
      { id: "M4", name: "LinkedIn Account-Based Marketing (ABM)", desc: "Target corporate decision-makers to generate B2B sales leads." },
      { id: "M5", name: "High-Converting Landing Page Design", desc: "Build web pages designed to capture contact details and drive sales." },
      { id: "M6", name: "Google Analytics 4 (GA4) Routing", desc: "Configure tracking rules, map custom event goals, and build dashboards." },
      { id: "M7", name: "Email Marketing via Mailchimp/Klaviyo", desc: "Design automated welcome emails, recovery carts, and product updates." },
      { id: "M8", name: "Conversion Rate Optimization (CRO)", desc: "A/B test page titles, button placements, and checkout steps to boost sales." },
      { id: "M9", name: "Retargeting & Remarketing Campaign Setup", desc: "Serve tailored ads to users who have previously visited your website." },
      { id: "M10", name: "Google Tag Manager Tracking Rules", desc: "Setup unified tracking tags to log user actions without slowing pages." },
      { id: "M11", name: "B2B Lead Generation Automation", desc: "Build forms that verify email addresses and export contacts directly to CRM." },
      { id: "M12", name: "Competitor Ad Creative Monitoring", desc: "Analyze competitors' active ads to identify successful marketing angles." },
      { id: "M13", name: "Customer Acquisition Cost (CAC) Auditing", desc: "Audit marketing spends to improve lead quality and lower costs." },
      { id: "M14", name: "WhatsApp Business Marketing Systems", desc: "Setup bulk messaging triggers, automated replies, and catalog displays." },
      { id: "M15", name: "SMS Text Messaging Blast Campaigns", desc: "Deliver promotional codes and reminders directly to customer phones." },
      { id: "M16", name: "Search Engine Optimization (SEO) Audits", desc: "Audit page load speeds, meta descriptions, and link profiles to boost rank." },
      { id: "M17", name: "UTM Tracking Link Implementation", desc: "Build tracking URLs to measure performance across channels." },
      { id: "M18", name: "HubSpot & Salesforce Integrations", desc: "Sync leads from landing pages to sales CRM databases automatically." },
      { id: "M19", name: "Viral Contest & Giveaway Frameworks", desc: "Setup promotions requiring social shares to join, expanding reach." },
      { id: "M20", name: "Customer Lifetime Value (LTV) Mapping", desc: "Build retention campaigns to increase lifetime value and repeat sales." },
      { id: "M21", name: "Cohort Retention Analytics Reports", desc: "Track user return rates over weeks to identify retention drops." },
      { id: "M22", name: "Google Display Network (GDN) Ad Setup", desc: "Design banner ads to build brand awareness across sites." },
      { id: "M23", name: "Affiliate & Partner Program Setups", desc: "Setup tracking platforms allowing partners to earn commissions on sales." },
      { id: "M24", name: "Influencer Campaign Strategy", desc: "Match brands with creators to execute product review campaigns." },
      { id: "M25", name: "Organic SEO Content Writing Plans", desc: "Plan articles targeting high-volume keywords to build organic traffic." },
      { id: "M26", name: "Negative Keyword Campaign Cleanses", desc: "Filter out irrelevant search terms in Google Ads to save budget." },
      { id: "M27", name: "A/B Dynamic Ad Headline Testing", desc: "Test multiple headline variations to boost click-through rates." },
      { id: "M28", name: "Google Merchant Center Product Feeds", desc: "Sync e-commerce product catalogs to display items on Google Shopping." },
      { id: "M29", name: "Cart Abandonment Recovery Automations", desc: "Send follow-up emails and WhatsApp reminders to recover abandoned carts." },
      { id: "M30", name: "SEO Competitor Keyword Gap Scans", desc: "Find high-volume keywords your competitors rank for that you lack." },
      { id: "M31", name: "Brand Positioning & Strategy Audits", desc: "Audit corporate messaging to align branding across touchpoints." },
      { id: "M32", name: "Paid Social Media Ad Budget Scaling", desc: "Scale successful ad sets without triggering performance drops." },
      { id: "M33", name: "Local SEO Business Profile Optimization", desc: "Claim and optimize profiles to rank high on local maps." },
      { id: "M34", name: "Google Ad Grant Setup for Non-Profits", desc: "Apply for and manage search ad credits for qualified non-profits." },
      { id: "M35", name: "Customer Review Generation Triggers", desc: "Send automated requests prompting clients to leave positive reviews." },
      { id: "M36", name: "User Session Recordings (Hotjar Setup)", desc: "Analyze screen recordings and heatmaps to locate website exit points." },
      { id: "M37", name: "B2B Cold Outreach Pipeline Setup", desc: "Setup personalized email outreach campaigns to contact target companies." },
      { id: "M38", name: "Event Tracking via Facebook Conversions API", desc: "Send server-side event data directly to Facebook to bypass ad blockers." },
      { id: "M39", name: "Interactive Lead Magnet PDFs Design", desc: "Design ebooks and templates to capture emails on landing pages." },
      { id: "M40", name: "Press Release Distribution Campaigns", desc: "Distribute company updates to news outlets to build brand backlinks." },
      { id: "M41", name: "Automated Lead Routing to Sales Teams", desc: "Assign incoming leads to sales reps based on region or size." },
      { id: "M42", name: "Dynamic Landings via Geo-IP Location", desc: "Shift landing page copy based on viewer country to personalize offers." },
      { id: "M43", name: "Marketing Report Dashboard Configs", desc: "Build central reporting dashboards to review performance metrics." },
      { id: "M44", name: "Product Packaging Design Support", desc: "Align physical product designs with online brand styling." },
      { id: "M45", name: "Viral Marketing Growth Loop Ideation", desc: "Design product features that naturally prompt users to invite friends." }
    ]
  },
  "social-media": {
    title: "Social Media Management",
    parent: "digital",
    tagline: "Build a highly engaged audience across all social platforms.",
    description: "Tailored content calendars, custom visual assets, organic audience building, daily interactions, and performance analytics updates.",
    services: [
      { id: "S1", name: "Social Profile Audits & Redesigns", desc: "Optimize bios, profile photos, and links to present a unified brand." },
      { id: "S2", name: "Monthly Content Calendar Outlines", desc: "Plan post timelines, visual styles, and copy drafts in advance." },
      { id: "S3", name: "Organic Instagram Growth Strategies", desc: "Build engagement using reels, stories, and interactive carousels." },
      { id: "S4", name: "Corporate LinkedIn Account Updates", desc: "Publish case studies and updates to build B2B brand presence." },
      { id: "S5", name: "Custom Graphic Design for Posts", desc: "Design unique images and carousels matching corporate brand guidelines." },
      { id: "S6", name: "Video Reel Visual Post-Production", desc: "Add subtitles, transitions, and audio tracks to short-form video clips." },
      { id: "S7", name: "TikTok Strategy & Trend Alignments", desc: "Match video content with trending audio tracks to expand reach." },
      { id: "S8", name: "Daily Community Engagement & Replies", desc: "Monitor profiles, reply to comments, and forward direct messages." },
      { id: "S9", name: "Influencer Outreach & Contract Setup", desc: "Find creators, negotiate campaign terms, and manage visual deliverables." },
      { id: "S10", name: "Monthly Performance Analytics Reports", desc: "Track follower growth, engagement rates, and link clicks." },
      { id: "S11", name: "Custom Link-In-Bio Page Design", desc: "Build mobile-friendly landing pages hosting all active campaign links." },
      { id: "S12", name: "Social Media Brand Tone Styling", desc: "Establish consistent messaging rules for post copy and replies." },
      { id: "S13", name: "Facebook Page Group Setup & Moderation", desc: "Build online communities to gather reviews and answer queries." },
      { id: "S14", name: "Social Account Hack Protection Setups", desc: "Configure two-factor auth and manage access tools to secure profiles." },
      { id: "S15", name: "Organic Hashtag & Keyword Research", desc: "Identify tags and terms to maximize post discoverability on search feeds." },
      { id: "S16", name: "YouTube Channel Management & Uploads", desc: "Upload videos with optimized descriptions, tags, and thumbnails." },
      { id: "S17", name: "Twitter/X Brand Growth Management", desc: "Build professional presence through thread writing and trend replies." },
      { id: "S18", name: "Social Media Ad Split-Testing", desc: "Edit different versions of ads to test visual variations on social feeds." },
      { id: "S19", name: "User-Generated Content (UGC) Plans", desc: "Design prompts that encourage customers to share photos using products." },
      { id: "S20", name: "Pinterest Catalog Feed Configurations", desc: "Pin portfolio images and product catalogs to drive referral traffic." },
      { id: "S21", name: "Interactive Instagram Stories Setup", desc: "Run polls, questions, and countdowns to boost follower interaction." },
      { id: "S22", name: "Social Listening & Keyword Monitoring", desc: "Monitor brand mentions and competitor reviews across social feeds." },
      { id: "S23", name: "Crisis Management & Response Planning", desc: "Draft response guidelines to handle customer complaints or PR crises." },
      { id: "S24", name: "YouTube Shorts Optimizations", desc: "Format vertical clips and write SEO titles to boost reach." },
      { id: "S25", name: "Direct Message Lead Funnels Setup", desc: "Setup automated chat replies to answer product queries on Instagram DM." },
      { id: "S26", name: "Holiday Campaign Concept Planning", desc: "Plan promotional offers and visual styles for major holiday events." },
      { id: "S27", name: "Custom Brand GIF & Sticker Creation", desc: "Create animated GIFs for use in Instagram and WhatsApp stories." },
      { id: "S28", name: "Social Video Script Outline Drafts", desc: "Draft visual hooks and calls-to-action for promotional videos." },
      { id: "S29", name: "Cross-Posting Workflow Automations", desc: "Link platforms to share posts across profiles automatically." },
      { id: "S30", name: "LinkedIn Executive Profile Management", desc: "Write posts for company founders to build thought leadership online." },
      { id: "S31", name: "Social Media Platform Feature Audits", desc: "Review new platform updates to adapt post styles and formatting." },
      { id: "S32", name: "Corporate Announcement Post Designs", desc: "Create high-end visuals to announce hires, funding, or awards." },
      { id: "S33", name: "Reddit Community Monitoring", desc: "Monitor forums for product mentions and participate in discussions." },
      { id: "S34", name: "Social Media Benchmark Competitor Analysis", desc: "Compare engagement metrics against competitors to refine strategy." },
      { id: "S35", name: "TikTok Shop Setup & Product Feeds", desc: "Sync product catalogs to sell items directly within the TikTok app." },
      { id: "S36", name: "Instagram Collab Post Orchestration", desc: "Publish joint posts with partners to combine and reach both audiences." },
      { id: "S37", name: "Live Stream Event Broadcasting Setups", desc: "Configure broadcast settings for live Q&As on YouTube and LinkedIn." },
      { id: "S38", name: "Behind-The-Scenes Video Capturing", desc: "Record BTS footage to showcase corporate culture and design processes." },
      { id: "S39", name: "Social Graphic Template Creation", desc: "Build editable templates in Canva allowing team members to post updates." },
      { id: "S40", name: "Vimeo Video Hosting Showcase Setup", desc: "Build professional video portfolios to display work on websites." },
      { id: "S41", name: "Threads organic campaign setups", desc: "Drive customer engagement through conversational posts on Threads." },
      { id: "S42", name: "Automated Message Routing to CRMs", desc: "Sync customer messages from social DMs directly to support desks." },
      { id: "M43", name: "Social Media Strategy Advisory", desc: "Provide strategic audits to align post formatting with brand goals." },
      { id: "M44", name: "Product Launch Visual Countdowns", desc: "Design visual sequences counting down to new product launches." },
      { id: "M45", name: "Geo-Targeted Content Customizations", desc: "Personalize posts to target audiences in specific cities or countries." }
    ]
  },
  "seo-performance": {
    title: "SEO & Performance Advisory",
    parent: "digital",
    tagline: "High organic search rankings and optimized site performance.",
    description: "Technical SEO configurations, core web vitals speed tuning, backlink profiles, metadata structures, and conversion analysis.",
    services: [
      { id: "P1", name: "Technical SEO Website Audits", desc: "Scan websites to flag crawl errors, broken links, and redirect issues." },
      { id: "P2", name: "Core Web Vitals Performance Tuning", desc: "Optimize images, lazy load resources, and compress scripts to boost speeds." },
      { id: "P3", name: "Google Search Console Configuration", desc: "Submit sitemaps, monitor coverage issues, and review search traffic." },
      { id: "P4", name: "On-Page SEO Keyword Optimizations", desc: "Structure page titles, headings, and copy to match target search queries." },
      { id: "P5", name: "XML Sitemap & Robots.txt Customizations", desc: "Configure index rules to guide search bots to key landing pages." },
      { id: "P6", name: "High-Quality Backlink Building Plans", desc: "Secure reviews and brand mentions to boost website authority rankings." },
      { id: "P7", name: "Local SEO Google Business Profile Setups", desc: "Claim and optimize local profiles to rank high on maps." },
      { id: "P8", name: "Semantic Schema Markup (JSON-LD)", desc: "Add code markup to display rich snippets and reviews in search feeds." },
      { id: "P9", name: "WordPress Speed Tuning & Caching Plugins", desc: "Install and configure caching plugins to optimize database loads." },
      { id: "P10", name: "Broken 301 Redirect Architecture", desc: "Map broken URLs to live paths to preserve search rankings." },
      { id: "P11", name: "Image Compression & Next-Gen Formats", desc: "Convert files to WebP/AVIF formats to speed up page render times." },
      { id: "P12", name: "Google Analytics 4 E-Commerce Tracking", desc: "Configure tracking to log checkouts, coupon codes, and product revenue." },
      { id: "P13", name: "Competitor Organic Rank Keyword Audits", desc: "Analyze competitors' keyword rankings to find content gaps." },
      { id: "P14", name: "Server-Side Caching (Varnish/Redis)", desc: "Setup caching layers to load static screens without database calls." },
      { id: "P15", name: "JavaScript Bundle Code Splitting", desc: "Configure builders to load code blocks only when needed, boosting speeds." },
      { id: "P16", name: "Internal Linking Hierarchical Plans", desc: "Connect related pages to help search bots index website content." },
      { id: "P17", name: "Mobile Usability Fixes", desc: "Optimize text sizes and button spacing to pass mobile-friendly audits." },
      { id: "P18", name: "Alt Text & Media Descriptions Tuning", desc: "Add descriptions to all images to rank in image search results." },
      { id: "P19", name: "Duplicate Content Sweeps & Canonical Tags", desc: "Resolve duplicate page issues using canonical tag references." },
      { id: "P20", name: "Domain Authority Reconstruction Campaigns", desc: "Disavow spam links and resolve security warnings to restore rankings." },
      { id: "P21", name: "Technical Speed Auditing (Lighthouse Reports)", desc: "Generate speed reports and track improvements over time." },
      { id: "P22", name: "Google PageSpeed Insights Fixes", desc: "Resolve layout shifts (CLS) and input delay (FID) warnings." },
      { id: "P23", name: "HREFLANG Multilingual SEO Routing", desc: "Map language variations of pages to display correct versions to users." },
      { id: "P24", name: "E-A-T Quality Guidelines Optimization", desc: "Improve author bios and source links to meet search quality standards." },
      { id: "P25", name: "E-Commerce SEO Catalog Optimizations", desc: "Optimize product categories and search filters to boost discoverability." },
      { id: "P26", name: "Database Query Indexing & Profiling", desc: "Tune database queries to speed up searches on dynamic sites." },
      { id: "P27", name: "HTTP/3 Protocol Implementations", desc: "Enable modern transfer protocols to reduce latency and speed up loads." },
      { id: "P28", name: "WordPress Database Cleaning", desc: "Clear legacy post edits, spam comments, and transients to clean databases." },
      { id: "P29", name: "Voice Search Optimization Strategy", desc: "Optimize content to answer conversational, long-tail search queries." },
      { id: "P30", name: "SEO Keyword Density Auditing", desc: "Scan pages to prevent keyword stuffing warnings and balance terms." },
      { id: "P31", name: "Hotjar UX Heatmap Analysis", desc: "Identify layout roadblocks where users exit or fail to convert." },
      { id: "P32", name: "Google Tag Manager Container Audits", desc: "Clean up legacy tracking scripts to speed up overall site loading." },
      { id: "P33", name: "Cloudflare Rocket Loader Speed Setups", desc: "Deconstruct Javascript render orders to show page text faster." },
      { id: "P34", name: "Content Decay Rank Restorations", desc: "Identify and update declining articles to restore search rankings." },
      { id: "P35", name: "PDF Document Search Engine Optimizations", desc: "Tag catalog PDFs to allow users to discover them on search feeds." },
      { id: "P36", name: "SSL Security Encryption Upgrade", desc: "Configure HSTS rules to guarantee secure HTTPS connections." },
      { id: "P37", name: "Domain Redirect Migrations", desc: "Manage domain changes with redirects to preserve search ranking history." },
      { id: "P38", name: "AMP (Accelerated Mobile Pages) Audits", desc: "Deploy lightweight mobile frameworks to speed up loading on mobile devices." },
      { id: "P39", name: "Site Search Log Conversions Analysis", desc: "Track what users search for on-site to identify new product needs." },
      { id: "P40", name: "DNS Server Latency Optimizations", desc: "Migrate DNS records to Cloudflare to reduce initial connection times." },
      { id: "P41", name: "Anchor Link Navigation Indexing", desc: "Setup table-of-contents jump links to display rich snippets in search." },
      { id: "P42", name: "Disavow File Updates (Google Disavow Tool)", desc: "Build list files of toxic links to submit to Google." },
      { id: "P43", name: "CSS/JS Minification Automations", desc: "Automate code minification within CI/CD pipelines to compress file sizes." },
      { id: "P44", name: "Organic SEO KPI Dashboard Configs", desc: "Build customized reporting panels tracking keyword rankings and traffic." },
      { id: "P45", name: "Page Content Structure Updates", desc: "Reorganize page headings to help search bots index content." }
    ]
  }
};
